### ISSUE TITLE
Tortuga.Chain.MappingException: 'Cannot map value of type System.String to property Gender of type Char.'

### ISSUE THREAD

**Issue by agrinei** [TortugaResearch/Tortuga.Chain#469]
Microsoft SQL Server 2019
Tortuga.Chain.SqlServer.MDS 4.1.0 (just released)

We have an AppUsers table which has a Gender column - char(1) not nullable. When trying to map the Gender column to the CLR char datatype we get the exception above.

Sample:

create table AppUsers (
  Id int not null,
  [Name] nvarchar(100) not null,
  Gender char(1) not null
)

public class AppUser
{
    public int Id { get; set; }
    public string Name { get; set; }
    public char Gender { get; set; }
}

Sql("select Name, Gender from AppUsers where Id = @id", new { id = 1 }).ToObjectOrNull<AppUser>().Execute();

**Comment by Grauenwolf** [comment]
I think I found all the places where the change needs to be made. Running the tests now.

**Comment by Grauenwolf** [comment]
Ok, it will be part of the 4.2 release.

**Comment by Grauenwolf** [comment]
Ok, I think I've chased down all of the possible Char scenarios. 

@agrinei feel free to reach out if you think I've missing anything.

**Comment by Grauenwolf** [comment]
Ugh, forgot `ToCharSet`.  Adding #475 to the list.

**Comment by Grauenwolf** [comment]
v4.2 ha been published. https://github.com/TortugaResearch/Tortuga.Chain/releases/tag/v4.2.0

**Comment by Grauenwolf** [comment]
Honestly, the best way to support a project like this is to help with feature design and testing. 

Progress requires motivation. And motivation comes from working with people who are using the library to solve their problems.

**Comment by Grauenwolf** [comment]
For example, four of the last seven features arose from this bug fix and things that naturally followed from it.

**Comment by agrinei** [comment]
That's great. I'm using the project for a long time and I see it as very mature and consistent. Anyway, if I find some room for improvement I'll be happy to share. Thank you again.

**Comment by Grauenwolf** [comment]
You're welcome.
