### ISSUE TITLE
SQL Server Parameter Lengths - SqlServerDataSource.GetByColumn

### ISSUE THREAD

**Issue by agrinei** [TortugaResearch/Tortuga.Chain#499]
This is the same as #402 #414 but for SqlServerDataSource.GetByColumn

When calling SqlServerDataSource.GetByColumn it doesn't use column max length definition to set string parameters what could generate multiple query plans. It does work when we call SqlServerDataSource.From

[IT USES COLUMN DEFINITION]
sqlServerDataSource.From("MY_TABLE_NAME", new { my_column_name = "COLUMN_VALUE" })

[IT DOESN'T USE COLUMN DEFINITION]
sqlServerDataSource.GetByColumn("MY_TABLE_NAME", "my_column_name", "COLUMN_VALUE")

Versions tested: 

Tortuga.Chain.SqlServer v.4.3.0
Tortuga.Chain.SqlServer.MDS v.4.3.0

**Comment by Grauenwolf** [comment]
Confirmed using test `GetByColumn(string dataSourceName, DataSourceType mode)`

**Comment by Grauenwolf** [comment]
`GetByColumn` calls `GetByKey`, so this will fix the latter as well.

**Comment by Grauenwolf** [comment]
This appears to also affect the Update/Delete By Key functions. Basically anything that doesn't use the `ParameterBuilderCallback`. So we can just create a universal `CreateParameter` method and move the guts of `ParameterBuilderCallback` into it.

**Comment by Grauenwolf** [comment]
All tests passing.

@agrinei Is this a current problem for you or can it wait for the next release?

**Comment by agrinei** [comment]
Well, my real need is SqlServerDataSource.Sql and I see how complex it is. Next release is fine.

**Comment by Grauenwolf** [comment]
Released in v4.4.0.

**Comment by Grauenwolf** [comment]
@agrinei Thank you for your help on these changes.

**Comment by agrinei** [comment]
I'm very thankful for your attention, @Grauenwolf

**Comment by Grauenwolf** [comment]
You're welcome. Feel free to reach out if you need anything else.
