### ISSUE TITLE
Simple Aggregators

### ISSUE THREAD

**Issue by Grauenwolf** [TortugaResearch/Tortuga.Chain#88]
Examples:
- Min().[materializer]
- Max().[materializer]
- Average().[materializer]
- Count().[materializer]
- Distinct().[materializer]
- Count()

These are returned as structs that hang off of the `ds.From(...)` method. 
The materializer will also be a scalar type.
## Materializer Changes

Materializers will expose:
- `UseAggregationColumns`
- `AggregationColumns`

Class `AggregationColumn`
- ColumnName ( may be *)
- AsColumnName
- AggregationType (as above plus `Custom` and `GroupBy`)
- SelectExpression (used for custom aggregates such as windowing functions)

The aforementioned struct will pass the correct information needed to create the `DesiredAggregationColumn`.

**Comment by mikilion** [comment]
Why does not distinguishing COUNT from COUNT_BIG?
```
Count()
CountBig()
```

**Comment by Grauenwolf** [comment]
For SQL Server, we will always use `CountBig()` unless someone can show me a reason not to. As far as I can tell, `Count()` is a legacy function from a time when databases were much smaller.

For other databases, we `Count()` is sufficient no matter how many rows you have.

**Comment by Grauenwolf** [comment]
Examples:
- `AsMin(columnName).ToXxx()`
- `AsMax(columnName).ToXxx()`
- `AsAverage(columnName).ToXxx()`
- `AsSum(columnName, distinct).ToXxx()`

The `AsCount()` option already exists.

These are returned as a `ScalarDbCommandBuilder` and hang off of the `ds.From(...)` method. 

SQL generation will be handled inside `FromTableOrView` and `FromTableValueFunction` classes. 

The `ScalarDbCommandBuilder` exposes the `ToXxx` methods we need to indicate which result type to use. (Except for `AsCount`, which is always a `long`.)

**Comment by Grauenwolf** [comment]
The SQL generation for the `AsCount` method can be re-implemented to match the pattern we're using for the other aggregates.

**Comment by Grauenwolf** [comment]
TableFunctions will also support this.

**Comment by Grauenwolf** [comment]
We're going to use "aggregate" not "aggregation".
